config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home' 
  get 'sessions/new'

  get 'admins/new'

  resources :admins do
    resources :posts
  end

  get 'posts/index'
 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  get 'success' => 'static_pages#success_page'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_many :posts

	validates :name, presence: true, length: {maximum: 25}, uniqueness: true
	validates :password, length: {minimum: 6}, presence: true

	has_secure_password 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
	before_action :logged_in_user, only: [:new, :edit]
  ################  standard actions
	def new
		@admin = Admin.find(params[:admin_id])
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.admin_id = params[:admin_id]
		@post.save
		redirect_to  '/posts/index'
		flash[:success] = "posted!"
	end

	def edit
		@admin = Admin.find(params[:admin_id])
		@post = Post.find(params[:id])
	end

	def update
		@admin = Admin.find(params[:admin_id])
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
		@post.save
		redirect_to '/posts/index'
	end

	def index
		@posts = Post.all
	end

	def show
		@admin = Admin.find(params[:admin_id])
		@post = Post.find(params[:id])
	end

	def delete
		
	end

	##################
	def post_params
		params.require(:post).permit(:title, :body)
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "you don't belong there"
			redirect_to root_path
		end

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	# sign in form
  	#name, password, password_confirmation
  end

  def create
  	@admin_name = params[:session][:name]
  	@admin = Admin.find_by(name: @admin_name)

  	if @admin && @admin.authenticate(params[:session][:password])
  		
  		log_in(@admin) 
      puts "current user: #{current_user}"
  		redirect_to "/success"
  	else
  		flash.now[:error] = "nope it did'nt work"
  		render 'new'
  	end
  end

  def destroy
    log_out
    puts logged_in?
    flash[:notice] = "you've been logged out"
    redirect_to root_path
  end
  
  def correct_user?
    #blank
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def success_page		
	end

	def home	
		puts "current user: #{current_user}, logged in? #{logged_in?}"
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		#@current_user = @current_user || User.find_by(id: user_id)
		@current_user ||= Admin.find_by(id: session[:admin_id])
	end

	def log_in(admin)
		session[:admin_id] =  admin.id
	end

	def logged_in?
		!current_user.nil?
 	end

	def log_out
		session[:admin_id] = nil
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>Find me in app/views/admins/new.html.erb</p>

app/views/layouts/_header.html.erb
<% if logged_in? %>
	<p> logged in </p>
	<p> <%= button_to "log out", logout_path(method: :post) %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>CodingBlog</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">	
	    <% flash.each do |message_type, message| %>
	    	<div class="alert alert-<%= message_type %>"><%= message %></div>
	    <% end %> 
			<h1 class='blog-title'> Adventures of a Wandering Web Developer </h1>
			<%= yield %>
		</div>
		<div class='link-box'>
			<a href="http://www.google.com">personal site</a>
			<p><a href="http://www.google.com">gitHub</a></p>
			<a href="http://www.google.com">guildHouse</a>
		</div>
	</body>
</html>

app/views/posts/edit.html.erb
<h3> revise this post </h3>

<%= form_for([@admin, @post], method: :patch) do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control'  %>

	<%= f.label :body %>
	<%= f.text_area :body, class: 'form-control', wrap: "hard" %>

	<%= f.submit "update" %>

<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post">
		<%= puts "admin id: #{post.admin_id}" %>	
		<h3 class='post-title'> <%= link_to  h(post.title).gsub(/\n/, '<br/>').html_safe , admin_post_path(admin_id: post.admin_id, id: post.id) %> </h3>
		<div class='post-body'> <%= h(post.body).gsub(/\n/, '<br/>').html_safe %> </div>
		<%= button_to "edit post", "/admins/#{post.admin_id}/posts/#{post.id}/edit", method: :get %>

	</div>
	<p></p>
<% end %>	

app/views/posts/new.html.erb
<h1>write new post:</h1>

<%= form_for([@admin, @post]) do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>			
	<%= f.label :body %>
	<%= f.text_area :body, class: 'form-control', wrap: "hard" %>

	<%= f.submit "submit", class: "btn btn-primary" %>

<% end %>

app/views/posts/show.html.erb
	<div class="post">
	
		<h3 class='post-title'> <%= h(@post.title).gsub(/\n/, '<br/>').html_safe %> </h3>
		<div class='post-body'> <%= h(@post.body).gsub(/\n/, '<br/>').html_safe %> </div>
		<%= button_to "edit post", "/admins/#{@post.admin_id}/posts/#{@post.id}/edit", method: :get %>
	</div>

app/views/static_pages/home.html.erb
<p> welcome to the home page </p>

<% if logged_in? %>

<%=link_to "make a new post","/admins/#{current_user.id}/posts/new"%>	

<% end %>

app/views/static_pages/success_page.html.erb
<p>it worked!</p>